### ISSUE TITLE
Cannot Build or Run using Docker

### ISSUE THREAD

**Issue by eliasstepanik** [radzenhq/radzen-blazor#1040]
Hello,
I tried building and Running my Projekt using Docker but ran into the following error:
`
2023-06-24 22:23:25 Unhandled exception. System.IO.DirectoryNotFoundException: /.nuget/packages/radzen.blazor/4.13.3/staticwebassets/
2023-06-24 22:23:25    at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
2023-06-24 22:23:25    at Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.<>c.<UseStaticWebAssetsCore>b__1_0(String contentRoot)
2023-06-24 22:23:25    at Microsoft.AspNetCore.StaticWebAssets.ManifestStaticWebAssetFileProvider..ctor(StaticWebAssetManifest manifest, Func2 fileProviderFactory)
2023-06-24 22:23:25    at Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.UseStaticWebAssetsCore(IWebHostEnvironment environment, Stream manifest)
2023-06-24 22:23:25    at Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.UseStaticWebAssets(IWebHostEnvironment environment, IConfiguration configuration)
2023-06-24 22:23:25    at Microsoft.AspNetCore.Hosting.BootstrapHostBuilder.RunDefaultCallbacks()
2023-06-24 22:23:25    at Microsoft.AspNetCore.Builder.WebApplicationBuilder..ctor(WebApplicationOptions options, Action1 configureDefaults)
2023-06-24 22:23:25    at Microsoft.AspNetCore.Builder.WebApplication.CreateBuilder(String[] args)
2023-06-24 22:23:25    at Program.<Main>$(String[] args) in C:\Users\elias\RiderProjects\ServerBlog\ServerBlog\Program.cs:line 8
`

I tried finding some error but found nothing.

After that I tried downgrading Radzen but that also didn´t work.
I don´t think something with my Projekt is wrong because I could build it before and changed nothing that could lead to that error.

Dockerfile

`FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["NotionBlog/NotionBlog.csproj", "NotionBlog/"]
RUN dotnet restore "NotionBlog/NotionBlog.csproj"
COPY . .
WORKDIR "/src/NotionBlog"
RUN dotnet build "NotionBlog.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "NotionBlog.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "NotionBlog.dll"]`

**Comment by enchev** [comment]
Hey @eliasstepanik,

I’m afraid that this is not related to Radzen.Blazor components. You can check this thread for details:
https://github.com/dotnet/aspnetcore/issues/19292
