### ISSUE TITLE
<RadzenSeriesDataLabels Visible="true" /> error

### ISSUE THREAD

**Issue by luzwales** [radzenhq/radzen-blazor#1132]
if I set <RadzenSeriesDataLabels Visible="true" />  Visible set to ·true·,  it will display error.
`fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'CzdbmlPg68whS6aQvww29WMhlXqCGtgAGOaXesL9gZQ'.
      System.NullReferenceException: Object reference not set to an instance of an object.
         at Radzen.Blazor.CartesianSeries`1.GetDataLabels(Double offsetX, Double offsetY)
         at Radzen.Blazor.RadzenLineSeries`1.GetDataLabels(Double offsetX, Double offsetY)
         at Radzen.Blazor.RadzenSeriesDataLabels.<Render>b__17_0(RenderTreeBuilder builder)
         at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
         at Radzen.Blazor.CartesianSeries`1.<>c__DisplayClass71_0.<RenderOverlays>b__0(RenderTreeBuilder builder)
         at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
         at Radzen.Blazor.RadzenChart.<BuildRenderTree>b__113_2(RenderTreeBuilder __builder2)
         at Microsoft.AspNetCore.Components.CascadingValue`1.Render(RenderTreeBuilder builder)
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)`

if I set Visible="false", it is OK. and I set  <RadzenSeriesDataLabels Visible="true" OffsetX="0" OffsetY="0"/>

**Describe the bug**

**To Reproduce**

Alternatively link your repo with a sample project that can be run.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by enchev** [comment]
Tried here both declared statically and runtime and didn't get any error:
https://blazor.radzen.com/line-chart
