### ISSUE TITLE
Sporadic JSException during the start

### ISSUE THREAD

**Issue by OndrejUzovic** [radzenhq/radzen-blazor#1162]
It seems there is a race condition issue causing an exception when the application starts.
If the exception occurs and I just refresh the web-page then everything is initialized correctly and the application works fine.

In my Blazor Server application I sporadically get the following exception:
```
[2023-09-20T11:46:22.745Z] Error: Microsoft.JSInterop.JSException: Could not find 'Radzen.mediaQuery' ('Radzen' was undefined).
Error: Could not find 'Radzen.mediaQuery' ('Radzen' was undefined).
    at https://localhost:44395/_framework/blazor.server.js:1:497
    at Array.forEach (<anonymous>)
    at s.findFunction (https://localhost:44395/_framework/blazor.server.js:1:465)
    at E (https://localhost:44395/_framework/blazor.server.js:1:2611)
    at https://localhost:44395/_framework/blazor.server.js:1:3499
    at new Promise (<anonymous>)
    at Ft.beginInvokeJSFromDotNet (https://localhost:44395/_framework/blazor.server.js:1:3480)
    at Ft._invokeClientMethod (https://localhost:44395/_framework/blazor.server.js:1:75072)
    at Ft._processIncomingData (https://localhost:44395/_framework/blazor.server.js:1:72696)
    at Ft.connection.onreceive (https://localhost:44395/_framework/blazor.server.js:1:67009)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Radzen.Blazor.RadzenMediaQuery.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

Any idea why does it happen or haw can I avoid it?

**Comment by akorchev** [comment]
This error happens if the Radzen.Blazor JS file fails to load for some reason (Radzen is undefined). You can't really avoid it as it could happen due to end-user browser settings.

**Comment by OndrejUzovic** [comment]
Are there any particular browser settings which can cause it?
(In my case when it happens then after F5 (refresh) the page is reloaded and everything works fine.)

**Comment by akorchev** [comment]
I don't know of any browser settings that can cause a JS file not to load.
