### ISSUE TITLE
HtmlEditor errors on StateHasChanged

### ISSUE THREAD

**Issue by ParkerRedford** [radzenhq/radzen-blazor#130]
I want to add some fancy features on my page, but it requires StateHasChanged. However, the RadzenHtmlEditor component keeps erroring out with "Cannot set property 'innerHTML' of null

Error: Microsoft.JSInterop.JSException: Cannot set property 'innerHTML' of null
TypeError: Cannot set property 'innerHTML' of null
    at Object.innerHTML (https://localhost:44388/script/Radzen.Blazor.js:950:21)
    at https://localhost:44388/_framework/blazor.server.js:1:70368
    at new Promise (<anonymous>)
    at e.beginInvokeJSFromDotNet (https://localhost:44388/_framework/blazor.server.js:1:70334)
    at https://localhost:44388/_framework/blazor.server.js:1:26441
    at Array.forEach (<anonymous>)
    at e.invokeClientMethod (https://localhost:44388/_framework/blazor.server.js:1:26411)
    at e.processIncomingData (https://localhost:44388/_framework/blazor.server.js:1:24222)
    at e.connection.onreceive (https://localhost:44388/_framework/blazor.server.js:1:17307)
    at WebSocket.i.onmessage (https://localhost:44388/_framework/blazor.server.js:1:46783)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at Radzen.Blazor.RadzenHtmlEditor.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)

**Comment by akorchev** [comment]
We will need a reproduction of this issue.

**Comment by ParkerRedford** [comment]
I could not reproduce the issue, but I ended up fixing the issue by removing protected override async Task OnParametersSetAsync() in my project
