### ISSUE TITLE
Split Button Broken

### ISSUE THREAD

**Issue by groogiam** [radzenhq/radzen-blazor#1334]
**Describe the bug**
I am getting the following unhandled javascript error when click a split button directly after loading my application.

```
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Cannot read properties of undefined (reading 'filter')
      TypeError: Cannot read properties of undefined (reading 'filter')
          at Object.closePopup (https://localhost:51992/_content/Radzen.Blazor/Radzen.Blazor.js:998:37)
          at https://localhost:51992/_framework/blazor.webassembly.js:1:3337
          at new Promise (<anonymous>)
          at Object.beginInvokeJSFromDotNet (https://localhost:51992/_framework/blazor.webassembly.js:1:3311)
          at Object.Gt [as invokeJSFromDotNet] (https://localhost:51992/_framework/blazor.webassembly.js:1:62569)
          at Object.Ii (https://localhost:51992/_framework/dotnet.7.0.15.tv5tlwg9qh.js:5:71974)
          at _mono_wasm_invoke_js_blazor (https://localhost:51992/_framework/dotnet.7.0.15.tv5tlwg9qh.js:14:103886)
          at https://localhost:51992/_framework/dotnet.wasm:wasm-function[313]:0x1d6b8
          at https://localhost:51992/_framework/dotnet.wasm:wasm-function[283]:0x1cae6
          at https://localhost:51992/_framework/dotnet.wasm:wasm-function[221]:0xe1d6
Microsoft.JSInterop.JSException: Cannot read properties of undefined (reading 'filter')
TypeError: Cannot read properties of undefined (reading 'filter')
    at Object.closePopup (https://localhost:51992/_content/Radzen.Blazor/Radzen.Blazor.js:998:37)
    at https://localhost:51992/_framework/blazor.webassembly.js:1:3337
    at new Promise (<anonymous>)
    at Object.beginInvokeJSFromDotNet (https://localhost:51992/_framework/blazor.webassembly.js:1:3311)
    at Object.Gt [as invokeJSFromDotNet] (https://localhost:51992/_framework/blazor.webassembly.js:1:62569)
    at Object.Ii (https://localhost:51992/_framework/dotnet.7.0.15.tv5tlwg9qh.js:5:71974)
    at _mono_wasm_invoke_js_blazor (https://localhost:51992/_framework/dotnet.7.0.15.tv5tlwg9qh.js:14:103886)
    at https://localhost:51992/_framework/dotnet.wasm:wasm-function[313]:0x1d6b8
    at https://localhost:51992/_framework/dotnet.wasm:wasm-function[283]:0x1cae6
    at https://localhost:51992/_framework/dotnet.wasm:wasm-function[221]:0xe1d6
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.JSInterop.Infrastructure.IJSVoidResult, Microsoft.JSInterop, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at Radzen.Blazor.RadzenSplitButton.OnClick(MouseEventArgs args)
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

It seems I am able to work around this issue by opening a dropdown elsewhere on the page prior to clicking the split button.

**To Reproduce**
1. Run application with a split button.
2. Click on the split button

Alternatively link your repo with a sample project that can be run.

**Expected behavior**
Javascript error should not occur.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Chrome
 - Version  4.24.0

**Comment by enchev** [comment]
Hey @groogiam,

This issue was fixed two weeks ago  - update your Radzen.Blazor to the latest. Make sure also you cleared your browser and application cache.
