### ISSUE TITLE
Could not find 'Radzen.createDatePicker' 

### ISSUE THREAD

**Issue by ExceptionBrasil** [radzenhq/radzen-blazor#1431]
After updating the system to the latest version, 4.28.3, the system presented the error below Procedure to reproduce Install the nuget version 4.28.4 through visual studio, in a Blazor Server project, use the DataPicker component, as follows
 <RadzenDatePicker @bind-Value="variable" DateFormat="dd/MM/yyyy" Change="OnChangeAction"></RadzenDatePicker>

--------Error---------
Error: Could not find 'Radzen.createDatePicker' ('createDatePicker' was undefined).
    at http://localhost:5191/_framework/blazor.server.js:1:734
    at Array.forEach (<anonymous>)
    at l.findFunction (http://localhost:5191/_framework/blazor.server.js:1:702)
    at _ (http://localhost:5191/_framework/blazor.server.js:1:5445)
    at http://localhost:5191/_framework/blazor.server.js:1:3238
    at new Promise (<anonymous>)
    at y.beginInvokeJSFromDotNet (http://localhost:5191/_framework/blazor.server.js:1:3201)
    at Yt._invokeClientMethod (http://localhost:5191/_framework/blazor.server.js:1:61084)
    at Yt._processIncomingData (http://localhost:5191/_framework/blazor.server.js:1:58559)
    at Yt.connection.onreceive (http://localhost:5191/_framework/blazor.server.js:1:52200)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at Radzen.Blazor.RadzenDatePicker`1.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

**Comment by akorchev** [comment]
Check this forum thread: https://forum.radzen.com/t/error-after-update-with-no-code-change/16773
