### ISSUE TITLE
Microsoft.JSInterop.JSException: Could not find 'Radzen.preventArrows after Update to 5.1.1

### ISSUE THREAD

**Issue by Wolfware2023** [radzenhq/radzen-blazor#1669]
I got a new error in my log after updating to Radzen 5.1.1:
```
Unhandled exception in circuit '"e5jF1eyakit5n_JsQnIsi_e33j6iIFufBl40s9COH24"'.
Microsoft.JSInterop.JSException: Could not find 'Radzen.preventArrows' ('Radzen' was undefined).
Error: Could not find 'Radzen.preventArrows' ('Radzen' was undefined).
    at https://mydomain.com/myproject/_framework/blazor.server.js:1:497
    at Array.forEach (<anonymous>)
    at i.findFunction (https://mydomain.com/myproject/_framework/blazor.server.js:1:465)
    at E (https://mydomain.com/myproject/_framework/blazor.server.js:1:2606)
    at https://mydomain.com/myproject/_framework/blazor.server.js:1:3494
    at new Promise (<anonymous>)
    at kt.beginInvokeJSFromDotNet (https://mydomain.com/myproject/_framework/blazor.server.js:1:3475)
    at https://mydomain.com/myproject/_framework/blazor.server.js:1:72077
    at Array.forEach (<anonymous>)
    at kt._invokeClientMethod (https://mydomain.com/myproject/_framework/blazor.server.js:1:72063)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at Radzen.Blazor.RadzenDropDown`1.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState
```

I was not able to reproduce this error myself yet. I will update to Radzen 5.1.3 and hope it will solve it.

**Comment by Wolfware2023** [comment]
It happened to one of the users of the blazor server webservice. If they ask, I can tell them to clear their caches. But from experience our users rarely do.
Is there anything, I as the developer could do to fix this for my user(s) without them needing to contact my department?

**Comment by akorchev** [comment]
You can register the JS file as [shown in our documentation](https://blazor.radzen.com/get-started/net8?theme=material3#js). By doing this the cache will invalidate automatically when the version changes.
