### ISSUE TITLE
Sporadic exception in DataGrid

### ISSUE THREAD

**Issue by OndrejUzovic** [radzenhq/radzen-blazor#173]
This is a sporadic and rare exception I get when the DataGrid is being displayed:
(my current version 3.6.7)

```
[2021-07-14T13:45:56.343Z] Error: Microsoft.JSInterop.JSException: Could not find 'Radzen.adjustDataGridHeader' ('Radzen' was undefined).
Error: Could not find 'Radzen.adjustDataGridHeader' ('Radzen' was undefined).
    at https://localhost:44395/_framework/blazor.server.js:1:67388
    at Array.forEach (<anonymous>)
    at e.findFunction (https://localhost:44395/_framework/blazor.server.js:1:67348)
    at b (https://localhost:44395/_framework/blazor.server.js:1:69090)
    at https://localhost:44395/_framework/blazor.server.js:1:70036
    at new Promise (<anonymous>)
    at e.beginInvokeJSFromDotNet (https://localhost:44395/_framework/blazor.server.js:1:70009)
    at https://localhost:44395/_framework/blazor.server.js:1:26293
    at Array.forEach (<anonymous>)
    at e.invokeClientMethod (https://localhost:44395/_framework/blazor.server.js:1:26263)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at Radzen.Blazor.RadzenGrid`1.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
```

**Comment by akorchev** [comment]
This error indicates that the Radzen JS file didn't load for some reason. You can try moving it up before the blazor JS file.

**Comment by OndrejUzovic** [comment]
This error is really very rare and so far I observed it only on the development machine.
Not loading that file seems like an development environment problem - therefore, let's close this issue.
