### ISSUE TITLE
Problem with Steps Component

### ISSUE THREAD

**Issue by silenuz** [radzenhq/radzen-blazor#329]
Radzen 3.14.1  Net 5.0  VS 2019

I noticed some possible problems with the Steps' component.  Yesterday I was trying to use it in a component in a new Blazor Server application.

While testing the appearance of things and trying to decide whether to use the Steps component or not, I noticed that if I closed the page while the page with the steps component was loaded that it would cause a list of 4 outer and 4 inner exceptions to be output to the Debug window.  I had 4 step items in the Steps component.

The main exception:
```
Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer: Warning: Unhandled exception rendering component: Cannot process pending renders after the renderer has been disposed.
Object name: 'Renderer'.
```

Outer exception repeated once for each step in Steps component:

```
System.ObjectDisposedException: Cannot process pending renders after the renderer has been disposed.
Object name: 'Renderer'.
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessPendingRender()
   at Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer.ProcessPendingRender()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged()
   at Radzen.Blazor.RadzenSteps.RemoveStep(RadzenStepsItem item)
   at Radzen.Blazor.RadzenStepsItem.Dispose()
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.Dispose()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.Dispose(Boolean disposing)
Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer: Warning: Unhandled exception rendering component: Cannot process pending renders after the renderer has been disposed.
Object name: 'Renderer'.
```

Inner Exception repeated once for each step in the stepItems collection:

```
---> (Inner Exception #1) System.ObjectDisposedException: Cannot process pending renders after the renderer has been disposed.
Object name: 'Renderer'.
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessPendingRender()
   at Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer.ProcessPendingRender()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged()
   at Radzen.Blazor.RadzenSteps.RemoveStep(RadzenStepsItem item)
   at Radzen.Blazor.RadzenStepsItem.Dispose()
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.Dispose()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.Dispose(Boolean disposing)<---
```
I have an older application here that uses Radzen 3.2.7 and when I tried to duplicate the problem using that application it seemed to function fine.

In case it was something misconfigured by me, I created a new Blazor Server application, added a single page with a Steps component, and a NavMenu link to the page, and while it exhibits slightly different behavoir then in my original application it still raises the same exceptions that are easily dupllicated.

* Create new Blazor Server application, using Net 5 and VS 2019
* Add Radzen using Nuget
* Edit Imports file to add Radzen imports
* Edit host file to add Radzen scripts
* Add page with Steps component and multiple steps
* Add link to page with Steps component to the NavMenu
* Start Application
* Click steps page link
* Click either counter or forecast link to load that page
* click Steps page to navigate back to the page with the Steps component
* close browser window, exceptions are printed.

Note no exceptions are printed if you navigate away from the page with the Steps component before closing the application, it only occurs when closing and the page is active.

For your convience attached is the solution I used to duplicate things, as mentioned to duplicate, load the brokensteps page, load counter or fetch, then back to the broken steps page and close the browser, and the exceptions are printed.

As mentioned I could not seem to duplicate this in 3.2.7.

[BrokenSteps.zip](https://github.com/radzenhq/radzen-blazor/files/7847386/BrokenSteps.zip)

**Comment by enchev** [comment]
Fixed with https://github.com/radzenhq/radzen-blazor/commit/03653fb65331aa72e668f5dc94946ee81efaadb2
