### ISSUE TITLE
Strange NullReferenceException in RadzenDataGrid

### ISSUE THREAD

**Issue by OndrejUzovic** [radzenhq/radzen-blazor#445]
During a scenario which changes column titles in RadzenDataGrid I get the following exception during the redraw:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Radzen.Blazor.RadzenDataGrid`1.UpdatePickableColumn(RadzenDataGridColumn`1 column, Boolean visible)
   at Radzen.Blazor.RadzenDataGridColumn`1.SetParametersAsync(ParameterView parameters)
```

It looks like the member selectedColumns in RadzenDataGrid is null and therefore the following assignment in the method UpdatePickableColumn results to null:
`var columnsList = (IList<RadzenDataGridColumn<TItem>>)selectedColumns;`

Do you have any idea what could be wrong? Can it be something I am getting wrong in my code causing the failure in RadzenDataGrid?
(Unfortunately I am not able to provide an example code causing this error.)
I am currently using 3.18.4 version.

**Comment by OndrejUzovic** [comment]
The problem is resolved in 3.18.6.
