### ISSUE TITLE
ContextMenu throws exception after opening and trying to change page.

### ISSUE THREAD

**Issue by victorgutmann** [radzenhq/radzen-blazor#485]
**Describe the bug**
Unexpected error after opening ContextMenu and then trying to navigate to another page on the site. 
This error occurs even on the demo component site.

**To Reproduce**
1. Go to 'https://blazor.radzen.com/contextmenu'
2. Right Click on button "Right Click Me" (can be any of the 3)
3. Click any other link that leaves the page, e.g., "Overview"
4. See error on the browser's developer console. The connection to the server is closed, so you must reload the page.

**Expected behavior**
No error and to be able to navigate through the site without reloading it.

**Screenshots**
![image](https://user-images.githubusercontent.com/39846541/173257222-c59125bd-66b4-484c-b945-6beeba6c3c8c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 102.0.5005.115

**Additional context**
Error:
[2022-06-12T23:09:46.191Z] Error: There was an error applying batch 15.
blazor.server.js:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'removeChild')
    at j (blazor.server.js:1:17100)
    at j (blazor.server.js:1:17070)
    at j (blazor.server.js:1:17070)
    at ae.applyEdits (blazor.server.js:1:21274)
    at ae.updateComponent (blazor.server.js:1:20504)
    at blazor.server.js:1:114506
    at Dn.processBatch (blazor.server.js:1:114878)
    at Tt.<anonymous> (blazor.server.js:1:129060)
    at blazor.server.js:1:71783
    at Array.forEach (<anonymous>)
[2022-06-12T23:09:46.329Z] Error: System.AggregateException: One or more errors occurred. (TypeError: Cannot read properties of null (reading 'removeChild'))
 ---> System.InvalidOperationException: TypeError: Cannot read properties of null (reading 'removeChild')
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InvokeRenderCompletedCallsAfterUpdateDisplayTask(Task updateDisplayTask, Int32[] updatedComponents)
   --- End of inner exception stack trace ---

**Comment by enchev** [comment]
Thanks for the report! It seems however that the problem can be reproduced only with Overview link:
![context-menu](https://user-images.githubusercontent.com/5804953/173291390-387ca53c-2113-498b-9ab9-6d85c6391db3.gif)
