### ISSUE TITLE
Error when opening a confirm dialog after making a dropdown selection.

### ISSUE THREAD

**Issue by groogiam** [radzenhq/radzen-blazor#753]
**Describe the bug**
I am randomly getting this error when showing a confirm dialog using the following code.

```csharp
public async Task<bool> ShowConfirmDialog(string message, string title= "Confirm")
    {
        var retval = await DialogService.Confirm(message, title, new ConfirmOptions
        {
            OkButtonText = "Ok",
            CancelButtonText = "Cancel",
            ShowClose = false
        });

        return retval == true;
    }
```
```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Cannot read properties of undefined (reading 'target')
      TypeError: Cannot read properties of undefined (reading 'target')
          at Radzen.closeAllPopups (https://localhost:51992/_content/Radzen.Blazor/Radzen.Blazor.js:840:38)
          at Object.openDialog (https://localhost:51992/_content/Radzen.Blazor/Radzen.Blazor.js:947:16)
          at https://localhost:51992/_framework/blazor.webassembly.js:1:3332
          at new Promise (<anonymous>)
          at Object.beginInvokeJSFromDotNet (https://localhost:51992/_framework/blazor.webassembly.js:1:3306)
          at Object.St [as invokeJSFromDotNet] (https://localhost:51992/_framework/blazor.webassembly.js:1:59960)
          at _mono_wasm_invoke_js_blazor (https://localhost:51992/_framework/dotnet.6.0.12.qkxds61loa.js:1:195300)
          at wasm://wasm/00971d3e:wasm-function[219]:0x1a492
          at wasm://wasm/00971d3e:wasm-function[167]:0xce60
          at wasm://wasm/00971d3e:wasm-function[166]:0xbd73
Microsoft.JSInterop.JSException: Cannot read properties of undefined (reading 'target')
TypeError: Cannot read properties of undefined (reading 'target')
    at Radzen.closeAllPopups (https://localhost:51992/_content/Radzen.Blazor/Radzen.Blazor.js:840:38)
    at Object.openDialog (https://localhost:51992/_content/Radzen.Blazor/Radzen.Blazor.js:947:16)
    at https://localhost:51992/_framework/blazor.webassembly.js:1:3332
    at new Promise (<anonymous>)
    at Object.beginInvokeJSFromDotNet (https://localhost:51992/_framework/blazor.webassembly.js:1:3306)
    at Object.St [as invokeJSFromDotNet] (https://localhost:51992/_framework/blazor.webassembly.js:1:59960)
    at _mono_wasm_invoke_js_blazor (https://localhost:51992/_framework/dotnet.6.0.12.qkxds61loa.js:1:195300)
    at wasm://wasm/00971d3e:wasm-function[219]:0x1a492
    at wasm://wasm/00971d3e:wasm-function[167]:0xce60
    at wasm://wasm/00971d3e:wasm-function[166]:0xbd73
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at Radzen.Blazor.Rendering.DialogContainer.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

**To Reproduce**

This seems to happen after changing a radzen dropdown value then clicking on a radzen button that calls the above code.

Alternatively link your repo with a sample project that can be run.

**Expected behavior**
Showing a confirm box should not result in an unhandled exception.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 and 11
 - Browser Chrome 108
 - Radzen 4.4.0
**Additional context**

**Comment by enchev** [comment]
I believe that we've fixed this several weeks ago:
https://github.com/radzenhq/radzen-blazor/commit/80a887b0d0a7cca5cf99561929f199c99f16cb79
I'm unable to reproduce such problem on our demos:
![image](https://user-images.githubusercontent.com/5804953/208367613-1b4245c9-7bb1-4179-90ab-9a190c40cdba.png)
![image](https://user-images.githubusercontent.com/5804953/208367695-9039a8f5-1c2e-45b0-a439-02725f9a2105.png)

**Comment by groogiam** [comment]
Looks like I had old 4.4.0 script cached in my browser after upgrading to 4.4.6. Its working after forcing the script to update. Thanks for your help.
